##===- clang/lib/Driver/Makefile ---------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

CLANG_LEVEL := ../..
LIBRARYNAME := clangDriver
SOURCES = Action.cpp \
          Arg.cpp \
          ArgList.cpp \
          CC1AsOptions.cpp \
          CC1Options.cpp \
          Compilation.cpp \
          Driver.cpp \
          DriverOptions.cpp \
          HostInfo.cpp \
          Job.cpp \
          OptTable.cpp \
          Option.cpp \
          Phases.cpp \
          Tool.cpp \
          ToolChain.cpp \
          Tools.cpp \
          Types.cpp \
          ToolChains/AuroraUX.cpp \
          ToolChains/Darwin.cpp \
          ToolChains/DarwinClang.cpp \
          ToolChains/DarwinGenericGCC.cpp \
          ToolChains/DragonFly.cpp \
          ToolChains/FreeBSD.cpp \
          ToolChains/GenericGCC.cpp \
          ToolChains/Linux.cpp \
          ToolChains/Minix.cpp \
          ToolChains/NetBSD.cpp \
          ToolChains/OpenBSD.cpp \
          ToolChains/TCE.cpp \
          ToolChains/Windows.cpp

include $(CLANG_LEVEL)/Makefile
